rem Execute test cases on the PC
call ..\PCTEST\mkwin32 DOL
call ..\PCTEST\mkwin32 QuoteInsertString
call ..\PCTEST\mkwin32 addval
call ..\PCTEST\mkwin32 bitop
call ..\PCTEST\mkwin32 case
call ..\PCTEST\mkwin32 comment
call ..\PCTEST\mkwin32 common
call ..\PCTEST\mkwin32 condition
call ..\PCTEST\mkwin32 crossref
call ..\PCTEST\mkwin32 defined
call ..\PCTEST\mkwin32 elsif
call ..\PCTEST\mkwin32 emptystr
call ..\PCTEST\mkwin32 emptyval
call ..\PCTEST\mkwin32 eset
call ..\PCTEST\mkwin32 exists
call ..\PCTEST\mkwin32 exit1
call ..\PCTEST\mkwin32 exit2
call ..\PCTEST\mkwin32 exit3
call ..\PCTEST\mkwin32 exit4
call ..\PCTEST\mkwin32 expression
call ..\PCTEST\mkwin32 foo
call ..\PCTEST\mkwin32 in
call ..\PCTEST\mkwin32 include
call ..\PCTEST\mkwin32 includePars
call ..\PCTEST\mkwin32 index
call ..\PCTEST\mkwin32 insert
call ..\PCTEST\mkwin32 keep
call ..\PCTEST\mkwin32 large
call ..\PCTEST\mkwin32 large2
call ..\PCTEST\mkwin32 loop
call ..\PCTEST\mkwin32 macro
call ..\PCTEST\mkwin32 message
call ..\PCTEST\mkwin32 misc
call ..\PCTEST\mkwin32 mod
call ..\PCTEST\mkwin32 neg
call ..\PCTEST\mkwin32 nonempty
call ..\PCTEST\mkwin32 oldloop
call ..\PCTEST\mkwin32 perf
call ..\PCTEST\mkwin32 pwsint
call ..\PCTEST\mkwin32 pwspa
call ..\PCTEST\mkwin32 pwspaesc
call ..\PCTEST\mkwin32 region
call ..\PCTEST\mkwin32 reopenoutput
call ..\PCTEST\mkwin32 set
call ..\PCTEST\mkwin32 stdout
call ..\PCTEST\mkwin32 stringchars
call ..\PCTEST\mkwin32 strlen
call ..\PCTEST\mkwin32 strsearch
call ..\PCTEST\mkwin32 tab
call ..\PCTEST\mkwin32 text
call ..\PCTEST\mkwin32 textblock
call ..\PCTEST\mkwin32 undef
call ..\PCTEST\mkwin32 undef2
call ..\PCTEST\mkwin32 val
