= smk(1) -- man page
include::shared/attributes-header.adoc[]

include::shared/attributes-custom.adoc[]

// Preamble
// ========

include::shared/warning-softlab.adoc[]


== NAME

smk -- ScannerMaker, generate lexical analysers


== SYNOPSIS

*smk* [-help] [<option> ...] <file>


== DESCRIPTION

*smk* is a scanner generator similar to lex but with many more options and generates scanners with much higher performance.
The performance is even better than a scanner generated by flex version 2.6.

Input is a description file with the tokens to be recognized, semantic actions etc. and output is generated source files ready for compilation.

ScannerMaker is well integrated with the other components of the ToolMaker package.


== ARGUMENTS

file::
  The name of the ScannerMaker description file.
  Default extension is _.smk_.


== OPTIONS

-help::
  Gives a brief help on the arguments and options to the *smk* program.
  For detailed information about options refer to the _ScannerMaker Reference Manual_.


== FILES

<file>.tmk::
  The ToolMaker Common Description file.
  Contains common definitions for all the Makers in the ToolMaker package.
  <file> is the name of the description file with any _.smk_ extension removed.
<file>.voc::
  The vocabulary file used by *smk*.
  <file> is the name of the description file with any _.smk_ extension removed.
<file>.sml::
  The list file produced by *smk*.
  <file> is the name of the description file with any _.smk_ extension removed.
<file>.smt::
  The intermediate tables produced used by *smk*.
  <file> is the name of the description file with any _.smk_ extension removed.


== SEE ALSO

{pmk1}, {lmk1}, {toolmake1}, {imp1} +
_ScannerMaker Reference Manual_ (part of the _ToolMaker Reference Manual_)


== BUGS

Please contact SoftLab about bugs and enhancements.


== AUTHOR

include::shared/email-contact.adoc[]


== NOTES

These manual pages corresponds to ToolMaker version {revnumber}.

Copyright (C) 1989–1995, SoftLab ab.
