# Makefile for imp		Date: 1991-09-06/tools@heffa 08:10:08/toolmake
#
# ToolMaker tools must be accessible via the PATH environment variable.
#
# The various xxQ-macros are intended for commandline additions to the
# make invocation.
#

# The environmental variable TMHOME should be set to the ToolMaker
# home library, eg /usr/local/ToolMaker

# ---------------------------------------------------------------------
# Modified 1995-01-23 by Thomas Lennartsson (thole@lion) to build on hp
# with gmake.
#
# NOTE: This file is intended for use on HP ONLY. It does NOT support
#       any other platform. Use gmake on this file.
#
# 

ROOT		= /home/projects/ToolMaker
TMBIN		= $(ROOT)/bin/bin-$(TMARCH)
INTLIB  	= $(ROOT)/library

RELEASEROOT	= $(ROOT)
RELEASELIB	= $(RELEASEROOT)/lib/c
RELEASEBIN	= $(RELEASEROOT)/bin/bin-$(TMARCH)
RELEASEMAN	= $(RELEASEROOT)/man/man1
RELEASEINC	= $(RELEASEROOT)/include

IMP		= $(TMBIN)/imp $(IMPQ)
PMK		= $(TMBIN)/pmk $(PMQ)
LMK		= $(TMBIN)/lmk $(LMQ)
SMK		= $(TMBIN)/smk $(SMQ)

LDFLAGS		= $(LQ) -lm

# _INCLUDE_POSIX_SOURCE must be defined if the -ansi flag is set
# in order to give access to time_t in sys/types.h (valid for hp
# only).

CC 		= $(GCC) -pedantic -Wall -Wno-switch #-D_INCLUDE_POSIX_SOURCE

# Set CFLAGS to default value. It is reset for debug target.
CFLAGS		= -O4 $(CQ)

GCC		= gcc2.6.0

LD		= gcc2.4.5	# gcc2.6.0 causes test case UNDEF.TST to fail!!!!!


IMPLIB = imp.a

.KEEP_STATE:

#--

VERSIONOBJECTS	= impParse.o impPaSema.o impErr.o impList.o impScan.o \
		  impScSema.o ast.o name.o impMacro.o timing.o

OBJECTS		= $(VERSIONOBJECTS) version.o

debug:
	@$(MAKE) DEBUG='-g $(CQ) ' -f GNUMakefile imp

trace all: imp

both: imp imp.a

imp: impobj
	

releaseSRC:
	chmod 664 impMacro.h
	cp impMacro.h $(INTLIB)
	install -f $(RELEASEINC) impMacro.h
	chmod 664 $(RELEASEINC)/impMacro.h
	install -f $(RELEASEMAN) imp.1
	chmod 664 $(RELEASEMAN) imp.1

releaseARCH: impobj
	chmod 664 $(IMPLIB)
	cp $(IMPLIB) $(INTLIB)/bin-$(TMARCH)
	-ranlib $(INTLIB)/bin-$(TMARCH)/$(IMPLIB)
	-ranlib $(IMPLIB)
	install -f $(RELEASEBIN) imp
	chmod 755 $(RELEASEBIN)/imp
	install -f $(RELEASEBIN) $(IMPLIB) 
	chmod 664 $(RELEASEBIN)/$(IMPLIB)
	-ranlib $(RELEASEBIN)/$(IMPLIB)

newversion:
	@-\rm [0-9]*_[0-9]*_[0-9]*.*
	@sh version.sh
	venum +c
	echo "cat > `ls [0-9]*_[0-9]*_[0-9]*.*` <<EOF" > version.sh
	echo "IMP" >> version.sh
	echo "Incremental Macro Processor" >> version.sh
	echo "EOF" >> version.sh
	cvs commit -m 'New Version' version.sh

RELEASE:
	@if test -r CVS/Tag ; then \
	  : ; \
	else \
	  echo This tree is not checked out from a Tag! ; \
	  echo RELEASE not allowed!! ; \
	  exit 1 ; \
	fi
	@if cvs status | egrep Status | egrep -v Up-to-date ; then \
		exit 1 ; \
	fi
	@$(MAKE) -f GNUMakefile releaseARCH releaseSRC

purify:	$(IMPLIB) imp.o
	purify $(CC) -o impp $(CFLAGS) imp.o $(IMPLIB) $(LDFLAGS)

impobj:	checkARCH $(TMARCH)

checkARCH:
	if test -f .arch ; then :; else echo "none" > .arch; fi
	-if test `cat .arch` != $(TMARCH); then \
	    rm *.o *.a;\
	    echo $(TMARCH) > .arch ; \
	fi

hp: $(IMPLIB)
	$(LD) -o imp imp.c $(IMPLIB) $(LDFLAGS)

$(IMPLIB): $(OBJECTS)
	ar rv $(IMPLIB) $(OBJECTS)
	-ranlib $(IMPLIB)
