%%SET foo(foo, fie, fum)
%%(foo)
%%(foo[0])
%%( foo [ 0 ] )
%%(foo[1])
%%(foo[2])
%%(foo[3])
%%(foo[4])
%%(foo[-1])
%%(foo[ - 1 ])
%%SET fie(2)
%%(foo[fie])
%%(foo[%%(fie)])
%%SET fie(2, hej)
%%(foo[fie])
%%(foo[%%(fie)])
%%SET fie(hej, hopp)
%%(foo[fie])
%%(foo[%%(fie)])
%%(foo[fum])
%%(1[5])
%%(%%(fie)[6])
