#!/bin/sh
echo -n "Purifying "
../imp -help 2> .revision
head -6 .revision |tail -1
for f in addval case comment common emptystr include keep macro misc pwspa val index includePars loop message expression stringchars emptyval condition defined in insert nonempty region set text eset exit1 exit2 exit3 exit4 system DOL crossref
do
    echo "-------------------------"
    echo "Imping $f.tst"
    echo "-------------------------"
    ../imp -u $f.tst 2> $f.purify
    echo "-------------------------"
done >imptest.log 2>&1
