// PAGE 22 -- ToolMaker System Description

// STATUS: All text OK (no xrefs).

= CONCEPTS AND ASSUMPTIONS

ToolMaker is a set of tools to generate the input analysing part of a complete tool, a ToolMaker-based _subsystem_.
A subsystem is denoted by a name -- a _system name_.
This system name may be prepended to many of the function and type names exported by a ToolMaker based subsystem, a _system prefix_.

The three main parts of a ToolMaker-based subsystem (the _scanner_, _parser_ and _lister_) may all be generated by the appropriate _Maker_, ParserMaker, ScannerMaker or ListerMaker.
Each Maker is controlled by a _description file_ in which information particular to the Maker is placed and a _ToolMaker common description file_ containing common information and options.

To create a complete tool, add your analysing modules to the ToolMaker generated modules and link the complete system.

Throughout this document the term _Maker_ will be used to refer to any of the different software tools included in the ToolMaker package.

ToolMaker generated parsers, scanners and listers are automatically interfaced to each other using common declarations and usages of _source positions_, _token codes_ and _error messages_.

// @CHECK: Should BEGIN be formatted as inline-code?

A _source position_ is a data structure describing a position in the input, this could for example point to the beginning of the '`BEGIN`' as the first token in a Pascal block.
This data structure may contain line, column and file information and is automatically collected by the generated scanner thus giving the implementor efficient handles for indicating errors and other information in relation to the analysed input.
Source positions could for example be stored as attributes in the decorated abstract syntax tree of the input.

The scanner combines the input characters into _tokens_ which also are represented in a data structure returned to the parser.
The information about which token was recognized is represented by a value in the token data structure, the _token code_.
The token structure may also contain additional user defined attributes such as integer or string values or the identifier name.

Errors often occur in the input and a ToolMaker based system is well prepared to handle, recover from and report the errors to the user.
The generated parser calls an error handler interface to report the syntax errors it encounters and recovers from.
The generated error handler module by default prepares this information into message logging calls to the Lister.
Such a call carries source position information, a reference to a message template and optionally additional information to be inserted into the message to form an actual _error message_ which can be shown in listings or retrieved through procedure calls.
The logging of messages is also available as functions to be used by the implementor for example in later, e.g semantic, passes of the analysis.
