// PAGE 206 -- ListerMaker Reference Manual

= THE LISTERMAKER COMMAND

The invocation of ListerMaker is performed by a command of the form

[.shell]
..................................
lmk [-help] [<options> ...] <file>
..................................

The special option `-help` gives a short help of available options and their meaning.


== Parameters

// @XREF: The ListerMaker Description File

The ListerMaker command takes only one argument, the name of a description file.
The description file contains a description of the lister to be generated using definitions as described in _The ListerMaker Description File_ on page 201.
The argument may appear anywhere on the command line except between an option name and its arguments.
The default extension for the ListerMaker description file is `.lmk`.


== Options

One or more options may be specified on the command line overriding any specified options in the _options section_ in the description file.

All options are available as command line options, the general format is:

[.shell]
............................
-[-]optionname [optionvalue]
............................

// @XREF: The Options Section

The option names corresponds exactly to the names given in the section _The Options Section_ on page 202.
The option value (if required) corresponds to allowed values of the option.
To turn an option on, one dash is used, to turn an option off two dashes are used.
For example, to turn the verbose option on, use `-verbose`, to turn it off, use `--verbose`, which is equivalent to specifying `NO VERBOSE` in the options section.

// @XREF: The Options Section
// @XREF: Command Line Option Format
// @XREF: ToolMaker System Description

Please refer to the corresponding options and directives in _The Options Section_ on page 202 for a detailed description of the various options.
The general command line option format is described in _Command Line Option Format_ in the _ToolMaker System Description_, page 40.

The special option

[.shell]
........
-help
........

// @XREF: The Options Section

produces a verbose listing of the usage format of the command.
Each argument and option are given a short explanation.
Refer to _The Options Section_ on page 202 for details on the various options.

// PAGE 207

In addition the following special option is available from the command line:

[.shell]
...........
-lmt <file>
...........

This options may be used to direct ListerMaker to write the intermediate tables on a file other than the default.
