// PAGE 45 -- ToolMaker System Description

// STATUS: XRefs

[appendix]
[[tm.PL0-Example]]
= The PL/0 Example

The following example is a ToolMaker subsystem, as described in the walkthrough in <<A ToolMaker Based System>>, generated by _**toolmake**_ for a SunOS (i.e. UNIX) environment and `ansi-c` as the target language.
The subsystems name is `pl0` [Wirth] and contains ToolMaker-based scanner, parser and lister modules.


== Directory Listing

The following listing shows the files that need to be maintained by the user from the PL/O example.

// @CHECK: Carefully compare to original scans!
[.shell]
........................................................
-rw-r--r--  1   tools   1680    May 31  11:29   Makefile
-rw-r--r--  1   tools   3220    May 31  11:29   pl0.c
-rw-r--r--  1   tools    414    May 31  11:29   pl0.pmk
-rw-r--r--  1   tools    305    May 31  11:29   pl0.smk
-rw-r--r--  1   tools   1082    May 31  11:29   pl0.lmk
-rw-r--r--  1   tools   3474    May 31  11:29   pl0.tmk
........................................................

This listing shows all the files for the complete PL/O frontend example, including objects and executable.

// @CHECK: Carefully compare to original scans!
[.shell]
............................................................
-rw-r--r--  1   tools    1680    May 31  11:29   Makefile
-rwxr-xr-x  1   tools   90112    May 31  11:30   pl0
-rw-r--r--  1   tools    3220    May 31  11:29   pl0.c
-rw-r--r--  1   tools     414    May 31  11:29   pl0.pmk
-rw-r--r--  1   tools     305    May 31  11:29   pl0.smk
-rw-r--r--  1   tools    1082    May 31  11:29   pl0.lmk
-rw-r--r--  1   tools    6294    May 31  11:30   p10.o
-rw-r--r--  1   tools    3474    May 31  11:29   pl0.tmk
-rw-r--r--  1   tools      27    May 31  11:29   pl0.voc
-rw-r--r--  1   tools    6723    May 31  11:29   pl0Err.c
-rw-r--r--  1   tools    6751    May 31  11:30   pl0Err.o
-rw-r--r--  1   tools   38145    May 31  11:30   pl0List_c
-rw-r--r--  1   tools    2539    May 31  11:30   pl0List.h
-rw-r--r--  1   tools   36299    May 31  11:30   pl0List.o
-rw-r--r--  1   tools   45095    May 31  11:29   pl0Parse.c
-rw-r--r--  1   tools     647    May 31  11:29   pl0Parse.h
-rw-r--r--  1   tools   27681    May 31  11:30   pl0Parse.o
-rw-r--r--  1   tools    1653    May 31  11:29   pl0PaSema.c
-rw-r--r--  1   tools    1850    May 31  11:30   pl0PaSema.o
-rw-r--r--  1   tools   15131    May 31  11:30   pl0Scan.c
-rw-r--r--  1   tools     946    May 31  11:30   pl0Scan.h
-rw-r--r--  1   tools   17571    May 31  11:30   pl0Scan.o
-rw-r--r--  1   tools   17571    May 31  11:30   pl0ScSema.o
-rw-r--r--  1   tools   17571    May 31  11:30   pl0ScSema.o
............................................................


[[pl0.ToolMaker-Description]]
== pl0.tmk -- The ToolMaker Description File

// PAGE 46

// @CHECK: Carefully compare to original scans!
// SYNTAX: ToolMaker description file + C

------------------------------
-------------------------------------------------------
-- pl0.tmk  Date: 1993-06-09/toolmake
--
-- Common ANSI-C definitions for all ToolMaker tools.
-------------------------------------------------------
-- Created:   1993-04-27/reibert@roo
-- Generated: 1993-06-09 14:48:30/toolmake v2,rO,c5
-------------------------------------------------------

%%OPTIONS
    Prefix 'pl0';

%%IMPORT
typedef int TmNatural;  /* A natural number. */
typedef int TmCode;     /* The type of a token code. */

%%END

%%SRCP Name TmSrcp;
    Row line %% TmNatural %1 %%;
    Column col %% TmNatural %1 %%;
    File file %% TmNatural %1 %%;
%END

%%TOKEN Name TmToken;
    Code code %% TmCode %1 %%;
    Srcp srcp %% TmSrcp %l %%;
    Attributes
        stringValue %% char %1[256] %%,
        integerValue %% int %1 %%;
%%END
------------------------------


[[pl0.Main-Program]]
== pl0.c -- The Main Program

// @CHECK: Carefully compare to original scans!
// SYNTAX: ToolMaker description file + C

------------------------------
/* pl0.c    Date: 1993-06-24/toolmake

   pl0 -- main program

   1.0 - 1993-06-24/
*/

#include <stdio.h>

#define PRIVATE static
#define PUBLIC

#ifndef FALSE
typedef int boolean;

#define FALSE 0
#define TRUE 1
#endif

#include "pl0Parse.h"
#include "pl0List.h"
#include "pl0Scan.h"


char *VERSION= "1.0";
char *NAME   = "PL/0 Analysis Tool";
char *USAGE= "Usage: pl0 [-h] [-l <name>] <in> [<out>]";

void summary(); /* Imported from parser */

/* -- DATA -- */

PRIVATE char
    *listFileName= NULL,
    *inFileName= NULL,
    *outFileName= NULL;


/* -- SUBROUTINES -- */
/*-----------------------------------------------------
    perr ( )

    A simple writer of error messages (onto stderr),
    If 'addendum' is NULL it will not be written.
*/
PUBLIC void perr(
    char sev,
    char *desc,
    char *add
)
{
    if (add==NULL)
        fprintf(stderr, "%s: %c! %s\n", NAME, sev, desc);
    else
        fprintf(stderr, "%s: %c! %s: %s\n", NAME, sev, desc, add);
    if (sev=='F' || sev=='S') exit(1);
}

/* -- Argument processing -- */

PRIVATE void processArgs(
    int argc,
    char *argv[]
)
{
    int i;

for (i=1; i<argc; ++i) {
    if (argv[i][0]=='-' && argv[i][1]) {
        switch (argv[i][1]) {
    case '1':
        listFileName= argv[++i];
        break;
    case 'h':
        printf("%s\n\n", USAGE);
        printf("Options:\n");
        printf(" -l <name> Set list file name\n");
        exit(0);
    default:
        perr('W', "unknown switch", argv[i]);
         break;
    }
    else if (inFileName==NULL) inFileName= argv[i];
    else if (outFileName==NULL) outFileName= argv[i];
    else perr('W', "unknown argument", argv[i]);
    }
}


/* -- MAIN -- */

PUBLIC main(
    int argc,
    char *argv[]
){
    boolean stdIn;

    processArgs(argc, argv);
    printf("%s - %s\n\n", NAME, VERSION);

    if (inFileName == NULL)
        perr('F', "No input file", NULL);

    stdIn= strcmp(inFileName,"-")==0;
    if (stdln)
        pl0LiInit(VERSION, "standard input",
                    pl0_ENGLISH_Messages);
    else
        pl0Lilnit(VERSION, inFileName,
                    pl0_ENGLISH_Messages);
    if (!pl0ScanEnter(inFileName)) {
        pl0Log(NULL, 199, sevFAT, inFileName);
        pl0List("", 0, 78, liTINY, sevALL);
    } else {
        pl0Parse();
        pl0ScanTerminate();
        if (stdIn) {/* This gives an idea of processing of
                       error messages */
            int i;
            char err[1024];
            TmSrcp srcp;

            /* Print a list on the terminal if any errors */
            for (i=1; pl0Msg(i, &srcp, err); i++)
                printf("\"-\" line %d: %s (column %d)\n",
                        srcp.line, err, srcp.col);
        } else {
            /* Print a TINY list on the terminal */
            pl0List("" 0, 78, liTINY, sevALL);
                summary();
            /* And a list file if asked to. */
            if (!stdIn && listFileName != NULL) {
                pl0List(listFileName, 60, 132, liFULL, sevALL);
                    summary();
            }
        }
    }
    pl0LiTerminate();
}
------------------------------
