// PAGE 234 -- Toolmake Reference Manual

= TOOLMAKE RUN-TIME USAGE

When using _**toolmake**_ you will normally go through two phases.
First specification, when you decide the subsystems name, target language, parts to use etc.
Each of the parts may be selected or deselected simply by typing its name, the contents level is selected by typing `level` followed by the level required.

// @GRAMMAR: term 'unclarities' doesn't exist!

The second phase is the generation phase when _**toolmake**_ (by using IMP) actually creates the proper files in your current directory.
In this phase you will only need to interact if any errors or unclarities are discovered.
The generation phase is automatically entered by giving an empty specification command (i.e. a carriage return without any input).

// @XREF: ToolMaker System Description

_**Toolmake**_ is built to be robust in interaction with the user (that's you), so you can always get help when asked a question by typing a question mark.
These properties in addition to the walk-through in _ToolMaker System Description_ should give you the aid needed.


== Subsystem Name

The initial question when _**toolmake**_ is started is

[.shell]
...............
Subsystem name?
...............

This question should be answered with the name your new ToolMaker-based system should have.
This name will be the basename for all description files, main program template and Makefile-target generated by _**toolmake**_.

// @XREF: section 3.1 on page 233

If the optional argument is used (see section 3.1 on page 233) that is used as the answer for this question and the question is not put.

The specified system name, target language along with the selected components and the contents level is then presented.
Then the _**toolmake**_ prompt appears.


== ToolMake Commands

At the prompt one of the commands listed below may be used.
The default command, which is executed if an empty command is entered, is presented within parenthesis.
For example

[.shell]
....................
toolmake (GENERATE)>
....................


=== GENERATE

The `generate` command will start the generation of the files (components) currently selected.
After completed generation _**toolmake**_ is terminated.
If any of the generated files already exists the user is required to confirm overwriting them.

// PAGE 235

=== QUIT

The `quit` command immediately terminates _**toolmake**_, without any generation of files.


=== ALL

To select all components supported, the `all` command can be used.
To select means that they are candidates for being generated when the generation phase is entered.


=== NONE

The `none` command is the opposite of the `all` command.
I.e. all components are deselected.


=== PARSER, SCANNER, LISTER, MAIN, MAKEFILE

These commands all toggle the selection of the corresponding component.
I.e. if the component is selected it will be deselected, and vice versa.


=== LEVEL

The `level` command takes one parameter which is one of

* `MINIMAL`
* `NORMAL`
* `EXAMPLE`

If the level is not specified in the command, _**toolmake**_ will prompt for it (together with the default value).


=== LANGUAGE

The target language to be used in the generated files can be set with the `language` command.
It also requires the language as a parameter.
Possible languages are

* C
* ANSI-C
* C++

If the language is not specified in the command _**toolmake**_ will prompt for it together with the default value in parenthesis.

// PAGE 236

=== VERBOSE

The `verbose` command toggles the setting of verbose mode.
When ON _**toolmake**_ prints some extra information during generation.


=== HELP

The command `help` will list the available commands together with a short description as opposed to the `?` which only lists the command names.


=== INFORMATION

The `information` command lists the current setting of the various options, such as selected components, target language and contents level.
