// PAGE 206 -- ListerMaker Reference Manual

= The ListerMaker Command

The invocation of ListerMaker is performed by a command of the form

[.shell]
..................................
lmk [-help] [<options> ...] <file>
..................................

The special option `-help` gives a short help of available options and their meaning.


[[lm.Parameters]]
== Parameters

The ListerMaker command takes only one argument, the name of a description file.
The description file contains a description of the lister to be generated using definitions as described in <<The ListerMaker Description File>>.
The argument may appear anywhere on the command line except between an option name and its arguments.
The default extension for the ListerMaker description file is `.lmk`.


[[lm.Options]]
== Options

One or more options may be specified on the command line overriding any specified options in the _options section_ in the description file.

All options are available as command line options, the general format is:

[.shell]
............................
-[-]optionname [optionvalue]
............................

The option names corresponds exactly to the names given in the section <<lm.Options-Section>>.
The option value (if required) corresponds to allowed values of the option.
To turn an option on, one dash is used, to turn an option off two dashes are used.
For example, to turn the verbose option on, use `-verbose`, to turn it off, use `--verbose`, which is equivalent to specifying `NO VERBOSE` in the options section.

Please refer to the corresponding options and directives in <<lm.Options-Section>> for a detailed description of the various options.
The general command line option format is described in <<Command Line Option Format>> in <<ToolMaker System Description>>.

The special option

[.shell]
........
-help
........

produces a verbose listing of the usage format of the command.
Each argument and option are given a short explanation.
Refer to <<lm.Options-Section>> for details on the various options.

// PAGE 207

In addition the following special option is available from the command line:

[.shell]
...........
-lmt <file>
...........

This options may be used to direct ListerMaker to write the intermediate tables on a file other than the default.
