// @PAGE 55 -- Part II

= ParserMaker Reference Manual

// @STATUS: All text OK (no xrefs).

// INTRODUCTION (p.59)

ParserMaker is a general and advanced tool for the construction and maintenance of language processors -- parsers.
ParserMaker system contains many features which makes it easy to use for various applications, facilities that are not common in similar systems.
General features of ParserMaker are:

* It generates highly optimized parsers for different target languages.
* It automatically generates a three level error recovery system from the grammar specification.
* It supports two different techniques for handling ambiguous grammars.
* It supports the creation of a system by a special description file and the possibility of inserting target dependent code in the input (semantic actions).
* It contains a mechanism for the support of synthesized attributes in the semantic actions.
* It is highly integrated with the other tools in SoftLab's ToolMaker.
* It supports multiple target languages, currently '`c`', '`ansi-c`' and '`c++`'.

The input description consists of a set of context free grammar productions, extended with target dependent code segments.
Output from ParserMaker consists of one or more complete programs recognizing the language specified as input.

This part of the ToolMaker documentation contains no description of the theory behind ParserMaker.
Knowledge about parsing theory, especially concerning LR-parsers, is required in order to fully understand the document.
Familiarity with the other tools in the ToolMaker family is also beneficial but not necessary.

:leveloffset: +1

include::part2-1_concepts.adoc[]

:leveloffset: 0
