#! /bin/csh -f

grep -v "%%SET pmHeader" $1.pmt | grep -v "%%SET pmVersion" | grep -v "%%SET pmCorrection" > $1.pmt.ref

foreach f ($1Pa*)
    cp $f $f.ref
end
foreach f ($1Err*)
    cp $f $f.ref
end
rm *.ref.ref
cp $1Common.h $1Common.h.ref
