# Makefile for toolmake			      Date: 1993-06-21/reibert@roo
#
# ---------------------------------------------------------------------
# Modified 1995-01-20 by Thomas Lennartsson (thole@lion) to build on hp
# with gmake.
#
# NOTE: This file is intended for use on HP ONLY. It does NOT support
#       any other platform. Use gmake on this file.
#
# 

ROOT		= /home/projects/ToolMaker
TMLIB		= $(ROOT)/lib/c/
TMBIN		= $(ROOT)/bin/bin-$(TMARCH)
INTLIB		= $(ROOT)/library

RELEASEROOT	= $(ROOT)
RELEASELIB	= $(RELEASEROOT)/lib/c/
RELEASEBIN	= $(RELEASEROOT)/bin/bin-$(TMARCH)/
RELEASEMAN	= $(RELEASEROOT)/man/man1


CC		= gcc
CFLAGS		= '-DTMHOME="/usr/local/ToolMaker"'\
		  $(DEBUG) $(CQ) $(INCLUDE)

INCLUDE		= -I../license -I../imp

LDFLAGS		= $(LQ) -static

LIBS    	= ../license/license.o ../imp/imp.a

VERSIONSRCS 	= toolmake.c spa.c system.c ask.c menue.c
VERSIONOBJECTS 	= toolmake.o spa.o system.o ask.o menue.o
VQ		= +t

OBJECTS 	= $(VERSIONOBJECTS) version.o

# Set DEBUG to default value. It is reset in the debug target.
DEBUG		= -O4 

.KEEP_STATE:

#--
debug:
	@$(MAKE) DEBUG='-g -DDBG' -f GNUMakefile toolmake

all: 	toolmake

toolmake: init checkARCH $(OBJECTS) $(LIBS)
	$(LINK.c) -o $@ $(OBJECTS) $(LIBS) 

init: ../license/license.h ../imp/impMacro.h version.h

checkARCH:
	if test -f .arch ; then :; else echo "none" > .arch; fi
	-if test `cat .arch` != $(TMARCH); then \
	    rm *.o; \
	    echo $(TMARCH) > .arch ; \
	fi

#--
release:
	@if cvs status | egrep Status | egrep -v Up-to-date ; then \
		exit 1 ; \
	fi
	make newversion releaseARCH releaseSRC
	cvs rtag toolmake`ls [0-9]*_[0-9]*_[0-9]*.* | sed s/\\\.//` toolmake

releaseSRC:
	for f in *.imp; \
	  do \
	    install -f $(RELEASELIB) $$f
	    chmod 664 $(RELEASELIB)/$$f
	done
	install -f $(RELEASEMAN) toolmake.1
	chmod 664 $(RELEASEMAN)/toolmake.1

releaseARCH: toolmake
	install -f $(RELEASEBIN) toolmake
	chmod 755 $(RELEASEBIN)/toolmake

RELEASE:
	@if test -r CVS/Tag ; then \
	  : ; \
	else \
	  echo This tree is not checked out from a Tag! ; \
	  echo RELEASE not allowed!! ; \
	  exit 1 ; \
	fi
	@if cvs status | egrep Status | egrep -v Up-to-date ; then \
		exit 1 ; \
	fi
	make newversion releaseARCH releaseSRC

#--
../license/license.h: $(INTLIB)/license.h
	@-[ ! -d ../license ] && mkdir ../license
	cp -p $(INTLIB)/license.h ../license/license.h

../license/license.o: $(INTLIB)/bin-$(TMARCH)/license.o
	@-[ ! -d ../license ] && mkdir ../license
	cp -p $(INTLIB)/bin-$(TMARCH)/license.o ../license/license.o

#--
../imp/imp.a: $(INTLIB)/bin-$(TMARCH)/imp.a
	@-[ ! -d ../imp ] && mkdir ../imp
	cp -p $(INTLIB)/bin-$(TMARCH)/imp.a ../imp/imp.a

../imp/impMacro.h: $(INTLIB)/impMacro.h
	@-[ ! -d ../imp ] && mkdir ../imp
	cp -p $(INTLIB)/impMacro.h ../imp

#--
version.c: $(VERSIONSRCS)
	-@rm [0-9]*_[0-9]*_[0-9]*.*
	@sh version.sh
	venum $(VQ)

version.h:
	-@rm [0-9]*_[0-9]*_[0-9]*.*
	@sh version.sh
	venum $(VQ) -c

newversion:
	-@rm [0-9]*_[0-9]*_[0-9]*.*
	@sh version.sh
	venum +c
	@echo "cat > `ls [0-9]*_[0-9]*_[0-9]*.*` <<EOF" > version.sh
	@echo "toolmake" >> version.sh
	@echo "initiator for ToolMaker tools" >> version.sh
	@echo "EOF" >> version.sh
	cvs commit -m 'New Version' version.sh

#--
clean:
	-rm *.o *~ core

veryclean: clean
	-rm toolmake

# EoF