#
TMARCH	= cygwin

all: tmk imp lmk smk pmk

.PHONY: tmk
tmk:
	cd tmk; make TMARCH=$(TMARCH)

.PHONY: imp
imp:
	cd imp; make TMARCH=$(TMARCH)

.PHONY: lmk
lmk:
	cd lmk; make TMARCH=$(TMARCH)

.PHONY: smk
smk:
	cd smk; make TMARCH=$(TMARCH)

.PHONY: pmk
pmk:
	cd pmk; make TMARCH=$(TMARCH)
