/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/types.h>


#define LICENSEPROG ((u_long)390091)
#define LICENSEVERS ((u_long)1)
#define LICENSE ((u_long)1)
extern int *license_1();
